apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testing-java-app
  name: testing-java-app
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-java-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testing-java-app
    spec:
      containers:
      - image: testing-java-app
        name: testing-java-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing-java-app
  name: testing-java-app
  namespace: semics
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testing-java-app
  type: ClusterIP
status:
  loadBalancer: {}
